2 autogenerate a unique qr code
CMPUT301W24T30/ScanPal pull request #52
Opened 2024-03-01 23:42 UTC by yifeng15

add_edit_event.xml is wrong. Need to fix it and implement the adding event.

2024-03-01 23:59 UTC, Logan9312 requested changes
Everything looks good, just added a couple comments where it seems like docstring is missing for Part 3 deliverables. I couldn't test because the fragment isn't hooked up yet so we can just re-test once more event functionality is complete. Seems good to merge for now.

Not sure if this will conflict with anything @adviislam10 has done though so it's worth discussing with him.

2024-03-01 23:59 UTC, Logan9312 commented on app/src/main/java/com/example/scanpal/AddEditEventFragment.java
> +public class AddEditEventFragment extends Fragment {
Needs docstring for class

2024-03-01 23:59 UTC, Logan9312 commented on app/src/main/java/com/example/scanpal/QRCodeGenerator.java
> +public class QRCodeGenerator {
Needs docstring for class

2024-03-01 23:59 UTC, Logan9312 commented on app/src/main/java/com/example/scanpal/EventController.java
> +        // Why not just call FirebaseFireStore.getInstance()?
Agreed, we should do this

2024-03-03 22:28 UTC, yifeng15 commented
Had to force push to revert back to the state before mergin with the main.

2024-03-03 22:33 UTC, Logan9312 approved these changes
Looks good to me

2024-03-03 22:48 UTC, Sundance636 approved these changes
Looks good!

2024-03-03 22:48 UTC, Nandan-18 approved these changes
looks good, tested and works as expected!

2024-03-03 22:49 UTC, merged