44 add a splash screen
CMPUT301W24T30/ScanPal pull request #62
Opened 2024-03-06 02:15 UTC by adviislam10

2024-03-06 03:16 UTC, Logan9312 approved these changes
Seems good

2024-03-06 06:18 UTC, Nandan-18 requested changes

2024-03-06 06:18 UTC, Nandan-18 commented on app/src/main/AndroidManifest.xml
> -
these need to be added back

2024-03-06 06:18 UTC, Nandan-18 commented on app/src/main/AndroidManifest.xml
> -        android:usesCleartextTraffic="true"
this param needs to be added back

2024-03-06 16:39 UTC, Logan9312 approved these changes

2024-03-06 16:42 UTC, Sundance636 approved these changes

2024-03-06 17:14 UTC, Nandan-18 approved these changes
works as expected

2024-03-06 17:41 UTC, Logan9312 approved these changes

2024-03-06 17:54 UTC, Sundance636 approved these changes
Looks good!

2024-03-06 18:16 UTC, Nandan-18 approved these changes

2024-03-07 00:02 UTC, Nandan-18 approved these changes

2024-03-07 00:16 UTC, Logan9312 approved these changes

2024-03-07 00:23 UTC, merged